name: 通用检查

on:
  push:
    branches: ["master", "beta", "stable"]
  pull_request:
    branches: ["master", "beta", "stable"]

  workflow_dispatch:

jobs:
  global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified

      - uses: raven-actions/actionlint@v1

      - uses: avto-dev/markdown-lint@v1
        with:
          args: ./*.md
