name: Docker 项目检查

on:
  push:
    branches: [$default_branch, $protected-branches]
  pull_request:
    branches: [$default_branch, $protected-branches]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build . --file Dockerfile --tag image_name:$(date +%s)
