name: 通用检查

on:
  push:
    branches: ["master", "beta", "stable"]
  pull_request:
    branches: ["master", "beta", "stable"]

  workflow_dispatch:

jobs:
  global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified

      - uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: false

      - uses: codacy/codacy-analysis-cli-action@master
        with:
          output: codacy.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      - uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: codacy.sarif

      - uses: actions/dependency-review-action@v3

      - uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
