name: Docker 项目检查

on:
  push:
    branches: ["master", "beta", "stable"]
  pull_request:
    branches: ["master", "beta", "stable"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build . --file Dockerfile --tag image_name:$(date +%s)
