name: nightly 发布

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: Nightly ${{ steps.date.outputs.date }}
          tag_name: nightly-${{ steps.date.outputs.date }}
          generate_release_notes: true
